// Hand-written sample GraphQL responses shaped exactly like the live Toptracer API.
// Values are realistic and in meters. Reusable by tests in other modules.

// Response for: query($m:GameMode!){ userClubs(gameMode:$m){ clubs { ... } } }
export const userClubsFixture = {
  data: {
    userClubs: {
      clubs: [
        {
          id: 'club-driver',
          clubType: 'Driver',
          clubTypeDisplayName: 'Driver',
          category: 'Wood',
          categoryDisplayName: 'Woods',
          nickname: 'Big Bertha',
          displayOrder: 1,
          isDefault: true,
          isHidden: false,
          averages: { carry: 210.4, total: 231.8 },
        },
        {
          id: 'club-7iron',
          clubType: 'Iron7',
          clubTypeDisplayName: '7-iron',
          category: 'Iron',
          categoryDisplayName: 'Irons',
          nickname: null,
          displayOrder: 7,
          isDefault: false,
          isHidden: false,
          averages: { carry: 138.2, total: 145.6 },
        },
        {
          id: 'club-pw',
          clubType: 'PitchingWedge',
          clubTypeDisplayName: 'Pitching wedge',
          category: 'Wedge',
          categoryDisplayName: 'Wedges',
          nickname: null,
          displayOrder: 11,
          isDefault: false,
          isHidden: false,
          averages: null,
        },
      ],
    },
  },
} as const;

// Response for: query($m,$o,$l){ gameSessionsByGameMode(...){ gameSessions { ... shots { ... } } } }
export const gameSessionsFixture = {
  data: {
    gameSessionsByGameMode: {
      gameSessions: [
        {
          id: 'session-1',
          gameMode: 'WhatsInMyBag',
          score: null,
          tracedShots: 3,
          isFinished: true,
          beginTimestamp: '2026-08-20T09:00:00.000Z',
          timestamp: '2026-08-20T09:45:00.000Z',
          hasLaunchMonitorStats: true,
          range: { name: 'Kungsbacka Golf Range' },
          shots: [
            {
              id: 'shot-1-1',
              legacyId: '10001',
              shotIndex: 0,
              gameMode: 'WhatsInMyBag',
              isHidden: false,
              clubType: 'Driver',
              userClub: { clubTypeDisplayName: 'Driver', category: 'Wood' },
              launchMonitorStats: { spinRate: 2650, clubHeadSpeed: 47.2, smashFactor: 1.48 },
              stats: {
                total: 234.1,
                carry: 212.7,
                flatCarry: 210.3,
                ballSpeed: 69.8,
                launchAngle: 12.4,
                landingAngle: 38.1,
                curve: 3.2,
                height: 28.6,
                hangTime: 6.1,
                offTargetLine: 4.5,
              },
            },
            {
              id: 'shot-1-2',
              legacyId: '10002',
              shotIndex: 1,
              gameMode: 'WhatsInMyBag',
              isHidden: true,
              clubType: 'Driver',
              userClub: { clubTypeDisplayName: 'Driver', category: 'Wood' },
              launchMonitorStats: { spinRate: 3100, clubHeadSpeed: 45.0, smashFactor: 1.41 },
              stats: {
                total: 180.2,
                carry: 165.9,
                flatCarry: 162.0,
                ballSpeed: 63.4,
                launchAngle: 9.8,
                landingAngle: 41.2,
                curve: -18.7,
                height: 22.1,
                hangTime: 5.2,
                offTargetLine: -32.4,
              },
            },
            {
              id: 'shot-1-3',
              legacyId: '10003',
              shotIndex: 2,
              gameMode: 'WhatsInMyBag',
              isHidden: false,
              clubType: 'Iron7',
              userClub: { clubTypeDisplayName: '7-iron', category: 'Iron' },
              launchMonitorStats: { spinRate: 6400, clubHeadSpeed: 37.5, smashFactor: 1.36 },
              stats: {
                total: 146.0,
                carry: 139.4,
                flatCarry: 138.1,
                ballSpeed: 51.0,
                launchAngle: 18.9,
                landingAngle: 47.5,
                curve: 1.1,
                height: 26.3,
                hangTime: 5.8,
                offTargetLine: 2.0,
              },
            },
          ],
        },
        {
          id: 'session-2',
          gameMode: 'WhatsInMyBag',
          score: null,
          tracedShots: 1,
          isFinished: false,
          beginTimestamp: '2026-08-22T16:10:00.000Z',
          timestamp: '2026-08-22T16:20:00.000Z',
          hasLaunchMonitorStats: false,
          range: null,
          shots: [
            {
              id: 'shot-2-1',
              legacyId: '10010',
              shotIndex: 0,
              gameMode: 'WhatsInMyBag',
              isHidden: false,
              clubType: 'PitchingWedge',
              userClub: null,
              launchMonitorStats: null,
              stats: null,
            },
          ],
        },
      ],
    },
  },
} as const;
